### ISSUE TITLE
Just for SSR?

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt-community/google-optimize-module#40]
I'm just confirming, this module is only for target: server, mode: universal (SSR) correct?

Any other way doesn't seem to make sense.

@pi0 @farzadso

**Comment by farzadso** [comment]
@hecktarzuli That was our initial plan.

Why doesn't it make sense for SPAs? Can't SPAs use Google Optimize?

**Comment by hecktarzuli** [comment]
My perception was this module was for server side rendering and server side experiments.

Yes SPAs can use GO, but it would make more sense for them to use GO's client side library and WYSIWUG editor as the first payload wouldn't be guaranteed to be the right DOM anyway.

Thanks for the insight!

**Comment by farzadso** [comment]
That's true @hecktarzuli 

I couldn't agree with you any more.

**Comment by hecktarzuli** [comment]
Since this was designed to work with both, I'll make sure to continue supporting that with my upcoming tweaks.
